# Generated by Django 3.2.9 on 2021-12-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_testapplication_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testapplication",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Заявка создана"),
                    (1, "Выполняется"),
                    (2, "Обрабатываются результаты"),
                    (3, "Заявка завершена"),
                ],
                default=0,
                verbose_name="Статус заявки",
            ),
        ),
    ]
